name: PPG Voice Analysis

on: [workflow_dispatch]

jobs:
  analyze:
    runs-on: ubuntu-22.04  # Более стабильная версия
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsox-fmt-mp3 sox ffmpeg
        
    - name: Install Python packages
      run: |
        pip install torch torchaudio librosa matplotlib numpy
        git clone --depth 1 https://github.com/interactiveaudiolab/ppgs.git
        cd ppgs && pip install -e . && cd ..
        echo "PYTHONPATH=$PYTHONPATH:$(pwd)/ppgs" >> $GITHUB_ENV
    
    - name: Verify file exists
      run: |
        if [ ! -f "sample.wav" ]; then
          echo "Error: sample.wav not found!"
          exit 1
        fi
        sox --info "sample.wav"
        
    - name: Run analysis
      run: |
        python run_ppg.py || exit 1
        
    - name: Upload results
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: ppg-results
        path: results/
        retention-days: 1
