name: PPG Voice Analysis

on: [workflow_dispatch]

jobs:
  analyze:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsox-fmt-mp3 sox ffmpeg
        sudo apt-get install -y libsndfile1
        
    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install torch==2.0.1 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cpu
        pip install librosa==0.10.0 matplotlib==3.7.1 numpy==1.24.3
        git clone --depth 1 https://github.com/interactiveaudiolab/ppgs.git
        cd ppgs && pip install -e . && cd ..
        echo "PYTHONPATH=$PYTHONPATH:$(pwd)/ppgs" >> $GITHUB_ENV
    
    - name: Verify environment
      run: |
        python -c "import torch; print(f'PyTorch: {torch.__version__}')"
        python -c "import librosa; print(f'Librosa: {librosa.__version__}')"
        
    - name: Run analysis
      run: |
        python run_ppg.py
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: ppg-results
        path: results/
